import React, { useState } from 'react'; import { createRoot } from 'react-dom/client'; import { BrowserRouter, Routes, Route, Link, useNavigate, useParams } from 'react-router-dom'; import './app.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
function Layout({ children }) { return <><header><Link to="/">Inventory Portal</Link></header><main>{children}</main><footer>© 2025 Inventory Portal</footer></>; }
function Home(){ const nav=useNavigate(); return <Layout>
<div className="hero"><h1>Inventory Portal</h1><div className="search"><input placeholder="Search equipment, accessories, ports, locations..."/><span>&#128269;</span></div><p className="hint">Use search operators for better results, e.g. "Dell", "Laptop", "192.168.*.*"</p></div>
<div className="cards">
<div className="card it"><div className="card-head"><h2>IT Accessory</h2><span className="chev">&#8250;</span></div><p>Browse and manage all IT accessories available in the inventory. Check stock availability, specifications and assign to users or locations.</p><h4>Browse Accessories</h4><select><option>Select Accessory Type</option><option>Laptop</option><option>LCD</option><option>Keyboard / Mouse</option><option>Docking Station</option><option>Printer</option><option>Network Printer</option></select>
{['Laptop','LCD','Keyboard / Mouse','Docking Station','Printer','Network Printer'].map(t=><button key={t} className="list-item" onClick={()=>nav('/login')}><span>{t}</span><span>&#8250;</span></button>)}
<button className="list-item cta" onClick={()=>nav('/portal/islamabad')}><span>Go to IT Accessory</span><span>&#8250;</span></button></div>
<div className="card pm"><div className="card-head"><h2>Port Mapping</h2><span className="chev">&#8250;</span></div><p>View and manage port mappings across the network. Track active ports, IP assignments and device connectivity in real-time.</p><div className="panel"><h3>Port Mapping Overview</h3>{['Map ports to devices and IP addresses','Monitor port status and availability','Track network connectivity','Manage and export port mappings'].map(i=><div key={i} className="check"><span>&#9989;</span> {i}</div>)}</div><button className="list-item cta" onClick={()=>nav('/portal/islamabad')}><span>Go to Port Mapping</span><span>&#8250;</span></button></div>
<div className="card dc"><div className="card-head"><h2>Data Centre</h2><span className="chev">&#8250;</span></div><p>Manage data centre assets including servers, storage, racks and other infrastructure. Monitor environment and resource utilization.</p><div className="panel"><h3>Data Centre Overview</h3>{['Track servers, storage and racks','Monitor power, cooling and space','Manage assets and maintenance','View real-time alerts and status'].map(i=><div key={i} className="check"><span>&#9989;</span> {i}</div>)}</div><button className="list-item cta" onClick={()=>nav('/portal/islamabad')}><span>Go to Data Centre</span><span>&#8250;</span></button></div>
</div></Layout> }
function Portal(){ const nav=useNavigate(); const { office } = useParams(); return <Layout><h1>Choose Portal Type</h1><div className="choices"><button onClick={()=>nav(`/login?location=${office}&role=user`)}>User Portal</button><button onClick={()=>nav(`/login?location=${office}&role=admin`)}>Admin Portal</button></div></Layout> }
function Login(){ const nav=useNavigate(), q=new URLSearchParams(location.search), [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''); const submit=async e=>{e.preventDefault(); setError(''); const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier,password,role:q.get('role')})}); const d=await r.json(); if(!r.ok)return setError(d.message); localStorage.setItem('session',JSON.stringify(d)); nav('/dashboard');}; return <Layout><h1>Login</h1><form onSubmit={submit}><input placeholder="Username or email" value={identifier} onChange={e=>setIdentifier(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error">{error}</p>}<button>Login</button></form><Link to="/signup">Create an account</Link></Layout> }
function Signup(){ const nav=useNavigate(), [form,setForm]=useState({fullName:'',email:'',username:'',password:'',location:'islamabad'}),[error,setError]=useState(''); const submit=async e=>{e.preventDefault();const r=await fetch(`${API}/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)return setError(d.message);nav('/login');};return <Layout><h1>Create account</h1><form onSubmit={submit}>{['fullName','email','username','password'].map(k=><input key={k} type={k==='password'?'password':'text'} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<select value={form.location} onChange={e=>setForm({...form,location:e.target.value})}><option value="islamabad">Islamabad</option><option value="karachi">Karachi</option></select>{error&&<p className="error">{error}</p>}<button>Sign up</button></form></Layout>}
function Dashboard(){const s=JSON.parse(localStorage.getItem('session')||'null');if(!s)return <Layout><p>Please <Link to="/">sign in</Link>.</p></Layout>;const {user}=s;return <Layout><h1>{user.role==='admin'?'Admin':'User'} Portal</h1><p>Welcome, {user.fullName}. You are signed in for the {user.location} office.</p><button onClick={()=>{localStorage.removeItem('session');location.href='/'}}>Sign out</button></Layout>};function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/portal/:office" element={<Portal/>}/><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/dashboard" element={<Dashboard/>}/></Routes>}createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
